version: "3"
services:
    api:
        build: .
        # depends on a service to start first
        depends_on:
            - postgres
        # <port on local machine>:<port on container where service is running>
        ports:
            - 8000:8000
        # bind the volume, to detect the changes instantly
        volumes:
            - ./:/usr/src/app:ro
        # to override the cmd in dockerfile
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=shanky123
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=shanky123
            - POSTGRES_DB=fastapi
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
